### ISSUE TITLE
Using this renderer, component doesn't actually render anything

### ISSUE THREAD

**Issue by Roeefl** [conorhastings/react-syntax-highlighter-virtualized-renderer#7]
Hello Conor,

I am trying to incorporate your virtualized-renderer into our component since our code snippets are often very heavy (around 5k lines of code on average) and render-expensive.

No matter what I tried, changed or modified, eventually removing every customization and trying to use it directly as it is in the example, 

Once the `renderer={virtualizedRenderer()}` prop is added, nothing is rendered:
![image](https://user-images.githubusercontent.com/10502198/79463432-856c2080-8001-11ea-9580-828cfce63222.png)

Once it's removed, customized completely or not at all, the code passed to the highlighter is rendered normally:
![image](https://user-images.githubusercontent.com/10502198/79463591-b187a180-8001-11ea-9a82-2a61607a75a5.png)

Kind of at a loss here since I tried literally everything I could think of.

Any help would be appreciated.
Thanks

**Comment by luciavelasco** [comment]
I had the same issue. Additional info: when I set `showLineNumbers` to true it _did_ render all the lines, but only the numbers - it didn't pass any text into into the second `<code>` element generated by the syntax highlighter.

**Comment by Roeefl** [comment]
@luciavelasco The same thing happened for me when I set `showLineNumbers` to true as well.

**Comment by pedromdav** [comment]
Facing the same issue. I've tried everything I can think of but I can't make it work.
Can we get a working example?

**Comment by hill84** [comment]
Fixable adding a specific height to the **hljs** container.

**Comment by travisdahl** [comment]
what @hill84 said will get it rendering...

```
  .yourWrapperDiv pre {
    height: 500px;
  }
  ```
  
```
<div className='yourWrapperDiv'>
      <SyntaxHighlighter
        ...
        renderer={virtualizedRenderer()}
      >
        {stuff}
      </SyntaxHighlighter>
</div>
```

**Comment by NadavShaar** [comment]
How can you set a specific height for each code-block determined by the number of rows?

**Comment by NadavShaar** [comment]
After some hacking, this worked for me with dynamic height:

```JSX
<SyntaxHighlighter
    className="syntaxHighlighter"
    style={vscDarkPlus}
    language="tsx"
    PreTag="div"
    renderer={virtualizedRenderer({ rowHeight: 18 })}
    lineNumberStyle={{ minWidth: 46 }}
    showLineNumbers
    {...props}
>
    {children}
</SyntaxHighlighter>
```

```CSS
.syntaxHighlighter {
    padding: 20px 20px 0 0 !important;

    & > code > div > div {
      height: auto !important;
    }

    .ReactVirtualized__Grid.ReactVirtualized__List {
      display: inline-block;
      overflow: unset !important;
    }

    // Removing last empty line
    .ReactVirtualized__Grid__innerScrollContainer > :last-child {
      display: none;
    }
}
```

Hope it helps :)
